--------------------------------------------------------
--  File created - Salı-Eylül-05-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOLGE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOLGE" 
   (	"ZONEID" NUMBER(10,0), 
	"ZONECODE" VARCHAR2(255 CHAR), 
	"ZONEISACTIVE" VARCHAR2(255 CHAR), 
	"ZONENAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BOLGE
SET DEFINE OFF;
Insert into SYSTEM.BOLGE (ZONEID,ZONECODE,ZONEISACTIVE,ZONENAME) values (1,'1','Aktif','1. Bölge');
Insert into SYSTEM.BOLGE (ZONEID,ZONECODE,ZONEISACTIVE,ZONENAME) values (2,'2','Aktif','2. Bölge');
Insert into SYSTEM.BOLGE (ZONEID,ZONECODE,ZONEISACTIVE,ZONENAME) values (52,'3','Aktif','3. Bölge');
Insert into SYSTEM.BOLGE (ZONEID,ZONECODE,ZONEISACTIVE,ZONENAME) values (102,'4','Aktif','4. Bölge');
Insert into SYSTEM.BOLGE (ZONEID,ZONECODE,ZONEISACTIVE,ZONENAME) values (152,'5','Aktif','5. Bölge');
--------------------------------------------------------
--  DDL for Index SYS_C0012542
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0012542" ON "SYSTEM"."BOLGE" ("ZONEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOLGE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOLGE" MODIFY ("ZONEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOLGE" ADD PRIMARY KEY ("ZONEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
